In [7]:
import tensorflow as tf
from dataset import load_dataset_from_tfrecord
import os
import cv2

print("TensorFlow version:", tf.__version__)
print("Is eager execution enabled?:", tf.executing_eagerly())

TensorFlow version: 2.15.0
Is eager execution enabled?: True


In [8]:
# Load the dataset
modalities = ['t2w', 't1w']
loaded_dataset = load_dataset_from_tfrecord(os.path.join('datasets', '_'.join(modalities) + '_dataset.tfrecord'), modalities)

# Print an example of the dataset
for example in loaded_dataset.take(1):
    print(example)
    print(example['t2w'].shape)
    print(example['t1w'].shape)


{'t2w': <tf.Tensor: shape=(256, 256, 1), dtype=float32, numpy=
array([[[0.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]],

       ...,

       [[0.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]]], dtype=float32)>, 't1w': <tf.Tensor: shape=(256, 256, 1), dtype=float32, numpy=
array([[[0.00784314],
        [0.00784314],
        [0.00784314],
        ...,
        [0.        ],
        [0.        ],
        [0.        ]],

       [[0.00784314],
        [0.00784314],
        [0.00784314],
        ...,
        [0.        ],
   

In [17]:
from tensorflow.keras import layers, models

def residual_block(x, filters, kernel_size=3, stride=1, conv_shortcut=False, name=None):
    print(f"{name}: Input shape:", x.shape)
    shortcut = x
    if conv_shortcut:
        shortcut = layers.Conv2D(filters, 1, strides=stride, padding='same', name=name+'_shortcut')(shortcut)
        shortcut = layers.BatchNormalization(name=name+'_shortcut_bn')(shortcut)
        print(f"{name}: Shortcut shape after conv:", shortcut.shape)

    x = layers.Conv2D(filters, kernel_size, strides=stride, padding='same', name=name+'_conv1')(x)
    x = layers.BatchNormalization(name=name+'_bn1')(x)
    x = layers.ReLU()(x)
    print(f"{name}: Shape after first conv:", x.shape)

    x = layers.Conv2D(filters, kernel_size, padding='same', name=name+'_conv2')(x)
    x = layers.BatchNormalization(name=name+'_bn2')(x)
    x = layers.Add()([x, shortcut])
    x = layers.ReLU()(x)
    print(f"{name}: Output shape:", x.shape)

    return x

def build_model():
    input1 = layers.Input(shape=(256, 256, 1), name='image1')
    input2 = layers.Input(shape=(256, 256, 1), name='image2')

    print("Input1 shape:", input1.shape)
    print("Input2 shape:", input2.shape)

    conv1_branch1 = layers.Conv2D(32, 3, strides=1, padding='same', name='conv1_branch1')(input1)
    conv1_branch2 = layers.Conv2D(32, 3, strides=1, padding='same', name='conv1_branch2')(input2)

    print("conv1_branch1 shape:", conv1_branch1.shape)
    print("conv1_branch2 shape:", conv1_branch2.shape)

    res_block_branch1 = residual_block(conv1_branch1, 32, name='res_block_branch1')
    res_block_branch2 = residual_block(conv1_branch2, 32, name='res_block_branch2')

    concatenated_features = layers.Concatenate(axis=-1)([res_block_branch1, res_block_branch2])
    print("Concatenated features shape:", concatenated_features.shape)

    res_block_concat = residual_block(concatenated_features, 64, name='res_block_concat')

    conv2 = layers.Conv2D(32, 3, strides=1, padding='same', name='conv2')(res_block_concat)
    conv3 = layers.Conv2D(1, 3, strides=1, padding='same', name='conv3')(conv2)

    sigmoid_output = layers.Activation('sigmoid')(conv3)
    weighted_avg_output = layers.Average()([sigmoid_output, input1, input2])

    print("Final output shape:", weighted_avg_output.shape)

    model = models.Model(inputs=[input1, input2], outputs=weighted_avg_output)
    return model

In [18]:
from loss_functions import ssim_loss

model = build_model()
# Print the model summary to understand the architecture
model.summary()

# For inspecting the shape of a specific layer's output:
for layer in model.layers:
    print(layer.name, layer.output_shape)
    
optimizer = tf.keras.optimizers.Adam(learning_rate=0.0001)

@tf.function
def train_step(image1, image2, model, optimizer):
    with tf.GradientTape() as tape:
        output = model([image1, image2], training=True)
        # Print the shape of the output to ensure it is compatible with the loss function
        print(output.shape)
        # Visualize the output
        loss = ssim_loss(image1, output)  # Ensure this is compatible with eager execution
    gradients = tape.gradient(loss, model.trainable_variables)
    optimizer.apply_gradients(zip(gradients, model.trainable_variables))
    return loss

for epoch in range(10):
    for example in loaded_dataset:
        image1, image2 = example['t2w'], example['t1w']
        loss_val = train_step(image1, image2, model, optimizer)
        print(f'Loss: {loss_val}')

Input1 shape: (None, 256, 256, 1)
Input2 shape: (None, 256, 256, 1)
conv1_branch1 shape: (None, 256, 256, 32)
conv1_branch2 shape: (None, 256, 256, 32)
res_block_branch1: Input shape: (None, 256, 256, 32)
res_block_branch1: Shape after first conv: (None, 256, 256, 32)
res_block_branch1: Output shape: (None, 256, 256, 32)
res_block_branch2: Input shape: (None, 256, 256, 32)
res_block_branch2: Shape after first conv: (None, 256, 256, 32)
res_block_branch2: Output shape: (None, 256, 256, 32)
Concatenated features shape: (None, 256, 256, 64)
res_block_concat: Input shape: (None, 256, 256, 64)
res_block_concat: Shape after first conv: (None, 256, 256, 64)
res_block_concat: Output shape: (None, 256, 256, 64)
Final output shape: (None, 256, 256, 1)
Model: "model_4"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 image1 (InputLayer)         [(No

ValueError: in user code:

    File "C:\Users\bianc\AppData\Local\Temp\ipykernel_25064\3257955466.py", line 20, in train_step  *
        loss = ssim_loss(image1, output)  # Ensure this is compatible with eager execution
    File "c:\Users\bianc\OneDrive\Documents\MTI830\multimodal-fusion\loss_functions.py", line 7, in ssim_loss  *
        return 1.0 - tf.reduce_mean(tf.image.ssim(true, pred, max_val))

    ValueError: Shapes (256, 256, 1) and (256, 1, 1) are incompatible


In [ ]:
model.save('models/model_tf2')